### ISSUE TITLE
Request - Please provide example .ecs-ami-deploy.yaml

### ISSUE THREAD

**Issue by mikeplem** [silinternational/ecs-ami-deploy#11]
Would it be possible to provide an example of the .ecs-ami-deploy.yaml file?

**Comment by Schparky** [comment]
Thanks for your interest, @mikeplem. I believe the config file is an incomplete feature. I'm not the original author of ecs-ami-deploy. It appears from looking at the source code that the config file is read from disk, but the config values are never used in the operation of the tool.
